In [8]:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.linalg import eigvals
import random

In [12]:
def matrix_power(matrix, power):
    """
    Calculates the power of a matrix.

    Parameters:
    matrix (numpy.ndarray): The matrix to calculate the power of.
    power (int): The power to raise the matrix to.

    Returns:
    numpy.ndarray: The resulting matrix.
    """
    return np.linalg.matrix_power(matrix, power)

def matrix_vector_multiplication(matrix, vector):
    """
    Calculates the multiplication of a matrix and a vector.

    Parameters:
    matrix (numpy.ndarray): The matrix to multiply.
    vector (numpy.ndarray): The vector to multiply.

    Returns:
    numpy.ndarray: The resulting vector.
    """
    return np.dot(matrix, vector)

def assign_random_values():
    # between -1, 1
    a = random.uniform(-1, 1)
    b = random.uniform(-1, 1)
    c = random.uniform(-1, 1)
    d = random.uniform(-1, 1)
    e = random.uniform(-1, 1)
    f = random.uniform(-1, 1)
    g = random.uniform(-1, 1)
    h = random.uniform(-1, 1)
    i = random.uniform(-1, 1)
    j = random.uniform(-1, 1)
    k = random.uniform(-1, 1)
    l = random.uniform(-1, 1)
    return a, b, c, d, e, f, g, h, i, j, k, l

def print_multiplication_until_n(G, q, n):
    """
    Prints the multiplication of matrix and vector for k = 1 to n.

    Parameters:
    G (numpy.ndarray): The matrix to multiply.
    q (numpy.ndarray): The vector to multiply.
    n (int): The number of times to multiply the matrix and vector.

    Returns:
    None
    """
    result = np.eye(4)
    for i in range(1, n+1):
        result += (-1)**i * matrix_power(G, i)
        print("Multiplication of matrix and vector for k = {}: {}".format(i, matrix_vector_multiplication(result, q)))

In [27]:
# our matrix
a, b, c, d, e, f, g, h, i, j, k, l = assign_random_values()

G = np.array([[0, a, b, c],[d, 0, e, f],[g, h, 0, i],[j, k, l, 0]])
# our vector
# choose a random vector
# q = np.random.rand(4)
q = np.array([1, 1, 1, 1])

print("Matrix G: " + str(G))
print("Vector q: " + str(q))
print("\n\n")

Matrix G: [[ 0.          0.78161634  0.97278245 -0.13016772]
 [-0.24813262  0.         -0.03358014  0.85513195]
 [ 0.91109465  0.19119147  0.         -0.33927386]
 [ 0.77283855  0.45197686 -0.27531001  0.        ]]
Vector q: [1 1 1 1]





In [28]:
# see if matrix powers converge
print(matrix_power(G, 500))
print("\n")
print(matrix_power(G, 501))

[[1.74214790e-10 2.33486764e-10 1.28729876e-10 1.39156824e-10]
 [7.24519234e-11 9.71017738e-11 5.35357942e-11 5.78721219e-11]
 [1.31667694e-10 1.76464144e-10 9.72912000e-11 1.05171657e-10]
 [1.36888413e-10 1.83461075e-10 1.01148867e-10 1.09341789e-10]]


[[1.66895177e-10 2.23676846e-10 1.23321306e-10 1.33310167e-10]
 [6.94078646e-11 9.30220546e-11 5.12864944e-11 5.54406317e-11]
 [1.26135692e-10 1.69050024e-10 9.32035220e-11 1.00752883e-10]
 [1.31137063e-10 1.75752980e-10 9.68991093e-11 1.04747807e-10]]


In [30]:
print_multiplication_until_n(G, q, 40)

Multiplication of matrix and vector for k = 1: [-0.62423107  0.42658081  0.23698774  0.05049461]
Multiplication of matrix and vector for k = 2: [0.44261272 0.80988644 1.50430648 1.35487028]
Multiplication of matrix and vector for k = 3: [-0.92002304  0.00174861  0.90156661  0.70603253]
Multiplication of matrix and vector for k = 4: [0.21350773 0.19823603 2.07743214 1.95844925]
Multiplication of matrix and vector for k = 5: [-0.92090717 -0.55199384  1.43202386  1.31733276]
Multiplication of matrix and vector for k = 6: [ 0.20987393 -0.30691289  2.39150669  2.3554515 ]
Multiplication of matrix and vector for k = 7: [-0.77992386 -0.88183815  1.66660724  1.63492459]
Multiplication of matrix and vector for k = 8: [ 0.28082723 -0.5356359   2.43387157  2.46015931]
Multiplication of matrix and vector for k = 9: [-0.62873245 -0.95234869  1.68121658  1.69513013]
Multiplication of matrix and vector for k = 10: [ 0.32956454 -0.54911348  2.33002906  2.37920399]
Multiplication of matrix and vector f