In [1]:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.linalg import eigvals
import random

In [22]:
def create_weighted_cycle_graph_adj_matrix(n):
    """
    Creates a weighted cycle graph with n nodes and returns its adjacency matrix.

    Parameters:
    n (int): Number of nodes in the graph.

    Returns:
    scipy.sparse.csr_matrix: Adjacency matrix of the graph.
    """
    # Create a cycle graph with n nodes
    G = nx.cycle_graph(n)

    # Add weights to the edges using random numbers
    for (u, v) in G.edges():
        G[u][v]['weight'] = np.random.rand()

    result = nx.adjacency_matrix(G, weight='weight')
    result = result.todense()
    # Return the adjacency matrix
    return result

def matrix_power(matrix, power):
    """
    Calculates the power of a matrix.

    Parameters:
    matrix (numpy.ndarray): The matrix to calculate the power of.
    power (int): The power to raise the matrix to.

    Returns:
    numpy.ndarray: The resulting matrix.
    """
    return np.linalg.matrix_power(matrix, power)

def matrix_vector_multiplication(matrix, vector):
    """
    Calculates the multiplication of a matrix and a vector.

    Parameters:
    matrix (numpy.ndarray): The matrix to multiply.
    vector (numpy.ndarray): The vector to multiply.

    Returns:
    numpy.ndarray: The resulting vector.
    """
    return np.dot(matrix, vector)


def print_multiplication_until_n(G, q, n):
    """
    Prints the multiplication of matrix and vector for k = 1 to n.

    Parameters:
    G (numpy.ndarray): The matrix to multiply.
    q (numpy.ndarray): The vector to multiply.
    n (int): The number of times to multiply the matrix and vector.

    Returns:
    None
    """
    result = np.eye(len(q))
    for i in range(1, n+1):
        result += (-1)**i * matrix_power(G, i)
        output_k = matrix_vector_multiplication(result, q)
        output_k = np.maximum(output_k, 0)
        print("k = {}: {}".format(i, output_k))

In [42]:
n = 5
G = create_weighted_cycle_graph_adj_matrix(n)

# our vector `q` is a vector with all entries equal to 1
q = np.ones(n)

print("Matrix G: \n" + str(G))
print("Vector q: " + str(q))
print("\n\n")

Matrix G: 
[[0.         0.32977466 0.         0.         0.06619797]
 [0.32977466 0.         0.75349925 0.         0.        ]
 [0.         0.75349925 0.         0.68215884 0.        ]
 [0.         0.         0.68215884 0.         0.93846309]
 [0.06619797 0.         0.         0.93846309 0.        ]]
Vector q: [1. 1. 1. 1. 1.]





/var/folders/hs/y116vr4j4yg5fcthw_l99c5r0000gn/T/ipykernel_6850/3592168269.py:18: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  result = nx.adjacency_matrix(G, weight='weight')


In [43]:
# print("Infinity norm of G: " + str(np.linalg.norm(G, ord=np.inf)))
# print("Norm-2 of G: " + str(np.linalg.norm(G)))
# print("Norm-1 of G: " + str(np.linalg.norm(G, ord=1)))
# # print sorted eigenvalues of G
# print("Eigenvalues of G: " + str(sorted(eigvals(G))))

In [44]:
print_multiplication_until_n(G, q, 40)

k = 1: [0.60402738 0.         0.         0.         0.        ]
k = 2: [1.02777018 1.12907512 1.48610956 1.30156224 1.54244538]
k = 3: [0.52555289 0.         0.         0.         0.        ]
k = 4: [1.17043718 1.38324271 2.34247385 1.77555181 2.33657697]
k = 5: [0.38916497 0.         0.         0.         0.        ]
k = 6: [1.42881754 1.81616002 3.77102381 2.55307399 3.59323561]
k = 7: [0.16321156 0.         0.         0.         0.        ]
k = 8: [1.86132525 2.53611855 6.11555381 3.83823445 5.6294792 ]
k = 9: [0. 0. 0. 0. 0.]
k = 10: [2.57267655 3.7282119  9.94872787 5.96506176 8.9483888 ]
k = 11: [0. 0. 0. 0. 0.]
k = 12: [ 3.73776806  5.70033341 16.21024947  9.48482098 14.36588822]
k = 13: [0. 0. 0. 0. 0.]
k = 14: [ 5.64413561  8.96194236 26.43672599 15.30866888 23.21244929]
k = 15: [0. 0. 0. 0. 0.]
k = 16: [ 8.76273797 14.35507924 43.13882025 24.94279955 37.66049458]
k = 17: [0. 0. 0. 0. 0.]
k = 18: [13.86428962 23.27101287 70.41807208 40.87670305 61.25848517]
k = 19: [0. 0. 0. 0

In [45]:
C = np.eye(n) + G
np.matmul(C, q)

matrix([[1.39597262, 2.08327391, 2.43565809, 2.62062192, 2.00466106]])

In [ ]:
"""
f(x) = c_0 + c_1 * x + c_2 * x^2 + ...

If the series converges for |x|<r, 
then the corresponding matrix series converges for matrices A such that ||A||<r 
for some matrix norm that satisfies ||AB||<||A|| ||B||
"""