In [1]:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.linalg import eigvals
import random

In [2]:
def matrix_power(matrix, power):
    """
    Calculates the power of a matrix.

    Parameters:
    matrix (numpy.ndarray): The matrix to calculate the power of.
    power (int): The power to raise the matrix to.

    Returns:
    numpy.ndarray: The resulting matrix.
    """
    return np.linalg.matrix_power(matrix, power)

def matrix_vector_multiplication(matrix, vector):
    """
    Calculates the multiplication of a matrix and a vector.

    Parameters:
    matrix (numpy.ndarray): The matrix to multiply.
    vector (numpy.ndarray): The vector to multiply.

    Returns:
    numpy.ndarray: The resulting vector.
    """
    return np.dot(matrix, vector)

def assign_random_values():
    # between -1, 1
    a = random.uniform(-1, 1)
    b = random.uniform(-1, 1)
    c = random.uniform(-1, 1)
    d = random.uniform(-1, 1)
    e = random.uniform(-1, 1)
    f = random.uniform(-1, 1)
    g = random.uniform(-1, 1)
    h = random.uniform(-1, 1)
    i = random.uniform(-1, 1)
    j = random.uniform(-1, 1)
    k = random.uniform(-1, 1)
    l = random.uniform(-1, 1)
    return a, b, c, d, e, f, g, h, i, j, k, l

def print_multiplication_until_n(G, q, n):
    """
    Prints the multiplication of matrix and vector for k = 1 to n.

    Parameters:
    G (numpy.ndarray): The matrix to multiply.
    q (numpy.ndarray): The vector to multiply.
    n (int): The number of times to multiply the matrix and vector.

    Returns:
    None
    """
    result = np.eye(4)
    for i in range(1, n+1):
        result += (-1)**i * matrix_power(G, i)
        print("Multiplication of matrix and vector for k = {}: {}".format(i, matrix_vector_multiplication(result, q)))

In [12]:
# our matrix
a, b, c, d, e, f, g, h, i, j, k, l = assign_random_values()
a = 0
b = 0.5
c = 0.5

G = np.array([[0, a, b, c],[d, 0, e, f],[g, h, 0, i],[j, k, l, 0]])
# our vector
# choose a random vector
# q = np.random.rand(4)
q = np.array([1, 1, 1, 1])

print("Matrix G: " + str(G))
print("Vector q: " + str(q))
print("\n\n")

Matrix G: [[ 0.          0.          0.5         0.5       ]
 [-0.91672444  0.          0.96444582 -0.3982591 ]
 [-0.11649623 -0.00566535  0.         -0.85884177]
 [-0.64056765  0.93146666  0.51265045  0.        ]]
Vector q: [1 1 1 1]





In [13]:
# see if matrix powers converge
print(matrix_power(G, 500))
print("\n")
print(matrix_power(G, 501))

[[ 4.14597091e+52 -1.98581504e+53 -1.31424408e+53 -2.61722387e+53]
 [ 6.17417785e+53 -3.10584537e+53 -4.58948767e+53  5.27856555e+53]
 [ 2.41284331e+53  8.70692531e+52 -6.13603021e+52  5.54815747e+53]
 [ 4.88727390e+53 -5.73151475e+53 -5.48566390e+53 -1.29436713e+53]]


[[ 3.65005860e+53 -2.43041111e+53 -3.04963346e+53  2.12689517e+53]
 [ 5.84047746e+49  4.94280886e+53  2.79772836e+53  8.26566384e+53]
 [-4.28067287e+53  5.17139996e+53  4.89042285e+53  1.38664834e+53]
 [ 6.72240852e+53 -1.17458161e+53 -3.74765636e+53  9.43758216e+53]]


In [14]:
print_multiplication_until_n(G, q, 40)

Multiplication of matrix and vector for k = 1: [0.         1.35053773 1.98100335 0.19645054]
Multiplication of matrix and vector for k = 2: [-0.08872695 -0.83233218  1.1763712  -1.27354312]
Multiplication of matrix and vector for k = 3: [ 1.04858596 -0.72308458 -0.10882384  1.11538683]
Multiplication of matrix and vector for k = 4: [0.49671851 2.51043204 2.07600059 2.40100801]
Multiplication of matrix and vector for k = 5: [-1.2385043   0.4093872   3.13417429 -2.08446457]
Multiplication of matrix and vector for k = 6: [ 0.47514514 -3.98826543 -0.932187   -1.78141218]
Multiplication of matrix and vector for k = 7: [ 2.35679959  1.6251574  -0.49719351  5.49718495]
Multiplication of matrix and vector for k = 8: [-1.49999572  5.82935592  6.00497743  1.25079612]
Multiplication of matrix and vector for k = 9: [-2.62788677 -5.66841716  1.93251746 -8.46915378]
Multiplication of matrix and vector for k = 10: [ 4.26831816 -6.64577397 -6.61191553  3.60589638]
Multiplication of matrix and vector f

In [ ]:
"""
f(x) = c_0 + c_1 * x + c_2 * x^2 + ...

If the series converges for |x|<r, 
then the corresponding matrix series converges for matrices A such that ||A||<r 
for some matrix norm that satisfies ||AB||<||A|| ||B||
"""