In [1]:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.linalg import eigvals
from itertools import combinations

In [2]:
def generate_subsets(n):
    # Generate all possible subsets of size 1 to n.
    for size in range(1, n + 1):
        for subset in combinations(range(n), size):
            yield subset
            # print(subset)

def check_p(matrix):
    n = len(matrix)

    # Compute the determinant of the whole matrix first.
    determinant = np.linalg.det(matrix)
    if determinant <= 0:
        return "Not a p-matrix"  # Return immediately if the whole matrix has a non-positive determinant

    # Check the determinants of diagonal elements (smallest subset) next.
    for i in range(n):
        submatrix = matrix[i, i]
        if submatrix <= 0:
            return "Not a p-matrix"  # Return immediately if any diagonal element is non-positive

    # Initialize the generator to get subsets.
    subset_generator = generate_subsets(n)

    # Check the determinants of other subsets.
    for subset in subset_generator:
        if len(subset) > 1:
            submatrix = matrix[np.ix_(subset, subset)]
            determinant = np.linalg.det(submatrix)
            if determinant <= 0:
                return "Not a p-matrix"  # Return immediately if a non-positive determinant is found

    return "All principal minors are positive -> p-matrix"


In [4]:
import numpy as np

def generate_non_symmetric_matrix(n):
    # Generate a random matrix with values between -1 and 1
    matrix = np.random.uniform(-1, 1, (n, n))

    # Set diagonal elements to 1
    np.fill_diagonal(matrix, 1)

    # Check sub-matrix determinants and adjust as needed
    for i in range(n):
        for j in range(i + 1, n):
            sub_matrix = matrix[:j+1, :j+1]  # Extract sub-matrix
            while np.linalg.det(sub_matrix) < 0:
                # Find a random element in the sub-matrix
                row_idx, col_idx = np.random.randint(0, j+1), np.random.randint(0, j+1)
                # Flip the sign of the element
                matrix[row_idx, col_idx] *= -1
    
    return matrix

# Define the size of the matrix (change n to your desired value)
n = 10
result_matrix = generate_non_symmetric_matrix(n)
print(result_matrix)

[[ 1.         -0.17863315  0.05221453  0.91410272  0.70620495  0.3580923
   0.89545707  0.43216547 -0.82933604  0.91879427]
 [-0.6748118   1.         -0.33100264  0.61621045 -0.2666039  -0.25603109
   0.34319887  0.98726942 -0.86216542 -0.63585693]
 [-0.94676594 -0.83190741  1.          0.99812274 -0.48292894 -0.260472
  -0.1868698   0.61879945 -0.15239615 -0.64795202]
 [-0.34587918 -0.31107598  0.31036253  1.         -0.07570927 -0.30787145
   0.59279649 -0.98097998 -0.12719642 -0.78584564]
 [-0.65348966 -0.4024412   0.31007921  0.69804764  1.          0.64690216
  -0.33139064  0.69508642 -0.99775764  0.5391532 ]
 [-0.47429664 -0.5475119  -0.3920254   0.82810538  0.53286766  1.
   0.05707014 -0.87856436  0.04851886  0.30295223]
 [ 0.21525069 -0.91963797  0.09677809  0.53576152 -0.00470704  0.94205666
   1.          0.68244322 -0.06817725  0.03734771]
 [ 0.70488668  0.36298922 -0.66415734 -0.39174758 -0.64872974  0.16608946
   0.32141385  1.         -0.36172951 -0.34177064]
 [ 0.318667

In [4]:
def schur_complement(matrix, block_indices):
    A = matrix[block_indices[0]:block_indices[1], block_indices[0]:block_indices[1]]
    B = matrix[block_indices[0]:block_indices[1], block_indices[1]:]
    C = matrix[block_indices[1]:, block_indices[0]:block_indices[1]]
    D = matrix[block_indices[1]:, block_indices[1]:]

    inv_D = np.linalg.inv(D)
    S = A - B @ inv_D @ C

    return S

# Create a random 4x4 matrix
matrix = generate_non_symmetric_matrix(4)

# Define the block indices for partitioning (e.g., block at row 2 and column 2)
block_indices = (2, 4)

# Compute the Schur complement
schur_matrix = schur_complement(matrix, block_indices)

print("Original Matrix:")
print(matrix)

print("\nSchur Complement:")
print(schur_matrix)

Original Matrix:
[[ 1.          0.41180866 -0.95501689  0.33562446]
 [-0.72924636  1.          0.04034673 -0.12964737]
 [ 0.14018943  0.19382237  1.         -0.62063751]
 [-0.50179487  0.48002998 -0.30126106  1.        ]]

Schur Complement:
[[ 1.         -0.62063751]
 [-0.30126106  1.        ]]


In [5]:
check_p(result_matrix)

'All principal minors are positive -> p-matrix'

In [10]:
n = 50
while check_p(result_matrix) == "Not a p-matrix":
    result_matrix = generate_non_symmetric_matrix(n)
    check_p(result_matrix)

KeyboardInterrupt: 