In [1]:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.linalg import eigvals
from itertools import combinations


In [13]:
a = 2
b = -0.5
matrix = np.array([[1, 1/a, 1/a], [1/a, 1, 1/b], [1/a, 1/b, 1]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

print("Determinant of the matrix is:", determinant)


Determinant of the matrix is: -4.5


In [2]:
# checking if a matrix is p-matrix

def generate_subsets(n):
    # Generate all possible subsets of size 1 to n.
    for size in range(1, n + 1):
        for subset in combinations(range(n), size):
            yield subset
            # print(subset)

def check_p(matrix):
    n = len(matrix)

    # Compute the determinant of the whole matrix first.
    determinant = np.linalg.det(matrix)
    if determinant <= 0:
        return "Not a p-matrix"  # Return immediately if the whole matrix has a non-positive determinant

    # Check the determinants of diagonal elements (smallest subset) next.
    for i in range(n):
        submatrix = matrix[i, i]
        if submatrix <= 0:
            return "Not a p-matrix"  # Return immediately if any diagonal element is non-positive

    # Initialize the generator to get subsets.
    subset_generator = generate_subsets(n)

    # Check the determinants of other subsets.
    for subset in subset_generator:
        if len(subset) > 1:
            submatrix = matrix[np.ix_(subset, subset)]
            determinant = np.linalg.det(submatrix)
            if determinant <= 0:
                return "Not a p-matrix"  # Return immediately if a non-positive determinant is found

    return "All principal minors are positive -> p-matrix"


In [60]:

def generate_non_symmetric_matrix(n):
    # Generate a random matrix with values between -1 and 1
    matrix = np.random.uniform(-1, 2, (n, n))

    # Set diagonal elements to 1
    np.fill_diagonal(matrix, 1)

    # # Check sub-matrix determinants and adjust as needed
    # for i in range(n):
    #     for j in range(i + 1, n):
    #         sub_matrix = matrix[:j+1, :j+1]  # Extract sub-matrix
    #         while np.linalg.det(sub_matrix) < 0:
    #             # Find a random element in the sub-matrix
    #             row_idx, col_idx = np.random.randint(0, j+1), np.random.randint(0, j+1)
    #             # Flip the sign of the element
    #             matrix[row_idx, col_idx] *= -1
    
    return matrix

# # Define the size of the matrix (change n to your desired value)
# n = 4
# result_matrix = generate_non_symmetric_matrix(n)
# print(result_matrix)

In [65]:
def schur_complement(matrix, block_indices):
    A = matrix[block_indices[0]:block_indices[1], block_indices[0]:block_indices[1]]
    B = matrix[block_indices[0]:block_indices[1], block_indices[1]:]
    C = matrix[block_indices[1]:, block_indices[0]:block_indices[1]]
    D = matrix[block_indices[1]:, block_indices[1]:]

    inv_D = np.linalg.inv(D)
    S = A - B @ inv_D @ C

    return S

block_indices = [0, 2]
matrix = generate_non_symmetric_matrix(4)
schur_matrix = schur_complement(matrix, block_indices)

print("Determinant of Schur Complement:")
print(np.linalg.det(schur_matrix))
print("Original Matrix:")
print(matrix)
print("\nSchur Complement:")
print(schur_matrix)

Determinant of Schur Complement:
-0.3846110287237953
Original Matrix:
[[ 1.          1.55496457  1.07409445  0.78787959]
 [-0.10254492  1.         -0.26370776  1.49137393]
 [ 0.8061432   1.32068156  1.          1.28029768]
 [ 1.15481471 -0.19734213  1.59857486  1.        ]]

Schur Complement:
[[ 0.20923863  1.43176606]
 [-0.12388548 -2.68586183]]
